#kadinio configuration file
#Sat Jun 14 08:17:49 EET 2025
Systray-Disabled=false
Look-And-Feel=Windows
Proxy-Server=
GUI-Disabled=false
Downlods-Location=./
Proxy-Port=80
exit-Disabled=false
Proxy-Manual=false
