#kadinio server configuration file
#Mon Dec 09 11:58:19 EET 2024
default-address=true
multihomed-enabled=false
server-address=127.0.0.1
username=kady
ssl-enabled=false
server-port=1099
reverse-connection=false
password=YQKQgI26amA\=
http-port=6666
