#kadinio viewer configuration file
#Wed Jan 08 14:57:41 EET 2025
default-address=false
multihomed-enabled=false
server-address=10.100.3.222
username=kady
ssl-enabled=false
server-port=8484
reverse-connection=false
password=YQKQgI26amA\=
http-port=6666
