package jrdesktop;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import jrdesktop.rmi.server.RMIServer;
import jrdesktop.server.Server;
import jrdesktop.viewer.ConnectionDialog;
import jrdesktop.viewer.Viewer;


public class HomeJPanel extends javax.swing.JPanel {

    /** Creates new form HomeJPanel */
    public HomeJPanel() {
        initComponents();
        updateStatus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaStatus = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonStartStop = new javax.swing.JButton();
        jButtonNewConnection = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonNewConnection1 = new javax.swing.JButton();

        jTextAreaStatus.setEditable(false);
        jTextAreaStatus.setBackground(new java.awt.Color(236, 233, 216));
        jTextAreaStatus.setColumns(17);
        jTextAreaStatus.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jTextAreaStatus.setRows(5);
        jTextAreaStatus.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));
        jTextAreaStatus.setMaximumSize(new java.awt.Dimension(160, 100));
        jTextAreaStatus.setMinimumSize(new java.awt.Dimension(160, 100));
        jScrollPane1.setViewportView(jTextAreaStatus);

        jButtonStartStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jrdesktop/images/player_play.png"))); // NOI18N
        jButtonStartStop.setText("Start");
        jButtonStartStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartStopActionPerformed(evt);
            }
        });

        jButtonNewConnection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jrdesktop/images/connect_creating.png"))); // NOI18N
        jButtonNewConnection.setText("Start a new connection");
        jButtonNewConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewConnectionActionPerformed(evt);
            }
        });

        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jrdesktop/images/exit.png"))); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonNewConnection1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jrdesktop/images/connect_creating.png"))); // NOI18N
        jButtonNewConnection1.setText("Start Kadinio");
        jButtonNewConnection1.setToolTipText("");
        jButtonNewConnection1.setDefaultCapable(false);
        jButtonNewConnection1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewConnection1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator1)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jButtonStartStop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonNewConnection1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonNewConnection)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonExit)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonStartStop)
                    .add(jButtonNewConnection)
                    .add(jButtonExit)
                    .add(jButtonNewConnection1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartStopActionPerformed
        if (RMIServer.serverConfig.reverseConnection){
            if (Viewer.isRunning())// {
                Viewer._Stop();
       //     jButtonNewConnection1.setEnabled(false);// }
            
            else {
                Viewer._Start(); }
        } else {
            if (Server.isRunning()) //{
                Server.Stop();
        //    jButtonNewConnection1.setEnabled(false);
       //     }
            else //{
                Server.Start();
           //  jButtonNewConnection1.setEnabled(true);
          //  }
            
        }
        updateStatus();
     //   jButtonNewConnection1.setEnabled(true);
}//GEN-LAST:event_jButtonStartStopActionPerformed

    private void jButtonNewConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewConnectionActionPerformed
        ConnectionDialog.main(null);
    }//GEN-LAST:event_jButtonNewConnectionActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        main.quit();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonNewConnection1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewConnection1ActionPerformed
      
        jrdesktop.viewer.ConnectionDialog.main(null);
        
        jrdesktop.main.close();
        
    }//GEN-LAST:event_jButtonNewConnection1ActionPerformed


    public void updateStatus() {
        if (RMIServer.serverConfig.reverseConnection)
            if (Viewer.isRunning()) {
                jTextAreaStatus.setText(Viewer.getStatus());
                jButtonStartStop.setText("Stop");
                jButtonStartStop.setIcon(new ImageIcon(Commons.STOP_ICON));
            } else {
                jTextAreaStatus.setText("Stopped.");
                jButtonStartStop.setText("Start");
                jButtonStartStop.setIcon(new ImageIcon(Commons.START_ICON));
            } else if (Server.isRunning()) {
                jTextAreaStatus.setText(Server.getStatus());
                jButtonStartStop.setText("Stop");
                jButtonStartStop.setIcon(new ImageIcon(Commons.STOP_ICON));
            } else {
                jTextAreaStatus.setText("Stopped.");
                jButtonStartStop.setText("Start");
                jButtonStartStop.setIcon(new ImageIcon(Commons.START_ICON));
            }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonNewConnection;
    private javax.swing.JButton jButtonNewConnection1;
    public static javax.swing.JButton jButtonStartStop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaStatus;
    // End of variables declaration//GEN-END:variables

}
